//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace  RequestService.RequestServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestType", Namespace="http://schemas.datacontract.org/2004/07/RequestService")]
    public enum RequestType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_SELDON = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_JUSTICE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_LEARNING = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequestCollection", Namespace="http://schemas.datacontract.org/2004/07/RequestService")]
    [System.SerializableAttribute()]
    public partial class UserRequestCollection : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private  RequestService.RequestServiceReference.JusticeRequestParams[] _JusticeRequestsParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private  RequestService.RequestServiceReference.LearningRequestParams[] _LearningRequestsParamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private  RequestService.RequestServiceReference.SeldonRequestParams[] _SeldonRequestsParamsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public  RequestService.RequestServiceReference.JusticeRequestParams[] _JusticeRequestsParams {
            get {
                return this._JusticeRequestsParamsField;
            }
            set {
                if ((object.ReferenceEquals(this._JusticeRequestsParamsField, value) != true)) {
                    this._JusticeRequestsParamsField = value;
                    this.RaisePropertyChanged("_JusticeRequestsParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public  RequestService.RequestServiceReference.LearningRequestParams[] _LearningRequestsParams {
            get {
                return this._LearningRequestsParamsField;
            }
            set {
                if ((object.ReferenceEquals(this._LearningRequestsParamsField, value) != true)) {
                    this._LearningRequestsParamsField = value;
                    this.RaisePropertyChanged("_LearningRequestsParams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public  RequestService.RequestServiceReference.SeldonRequestParams[] _SeldonRequestsParams {
            get {
                return this._SeldonRequestsParamsField;
            }
            set {
                if ((object.ReferenceEquals(this._SeldonRequestsParamsField, value) != true)) {
                    this._SeldonRequestsParamsField = value;
                    this.RaisePropertyChanged("_SeldonRequestsParams");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JusticeRequestParams", Namespace="http://schemas.datacontract.org/2004/07/RequestService")]
    [System.SerializableAttribute()]
    public partial class JusticeRequestParams :  RequestService.RequestServiceReference.BaseRequestParams {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string courtAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string debtorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loyerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string courtAddress {
            get {
                return this.courtAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.courtAddressField, value) != true)) {
                    this.courtAddressField = value;
                    this.RaisePropertyChanged("courtAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string debtorName {
            get {
                return this.debtorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.debtorNameField, value) != true)) {
                    this.debtorNameField = value;
                    this.RaisePropertyChanged("debtorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loyerName {
            get {
                return this.loyerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.loyerNameField, value) != true)) {
                    this.loyerNameField = value;
                    this.RaisePropertyChanged("loyerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LearningRequestParams", Namespace="http://schemas.datacontract.org/2004/07/RequestService")]
    [System.SerializableAttribute()]
    public partial class LearningRequestParams :  RequestService.RequestServiceReference.BaseRequestParams {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string courseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lectorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string course {
            get {
                return this.courseField;
            }
            set {
                if ((object.ReferenceEquals(this.courseField, value) != true)) {
                    this.courseField = value;
                    this.RaisePropertyChanged("course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lector {
            get {
                return this.lectorField;
            }
            set {
                if ((object.ReferenceEquals(this.lectorField, value) != true)) {
                    this.lectorField = value;
                    this.RaisePropertyChanged("lector");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeldonRequestParams", Namespace="http://schemas.datacontract.org/2004/07/RequestService")]
    [System.SerializableAttribute()]
    public partial class SeldonRequestParams :  RequestService.RequestServiceReference.BaseRequestParams {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime garanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Version seldonVersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime garante {
            get {
                return this.garanteField;
            }
            set {
                if ((this.garanteField.Equals(value) != true)) {
                    this.garanteField = value;
                    this.RaisePropertyChanged("garante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Version seldonVersion {
            get {
                return this.seldonVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.seldonVersionField, value) != true)) {
                    this.seldonVersionField = value;
                    this.RaisePropertyChanged("seldonVersion");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequestParams", Namespace="http://schemas.datacontract.org/2004/07/RequestService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof( RequestService.RequestServiceReference.LearningRequestParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof( RequestService.RequestServiceReference.SeldonRequestParams))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof( RequestService.RequestServiceReference.JusticeRequestParams))]
    public partial class BaseRequestParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequestServiceReference.IRequestService")]
    public interface IRequestService {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IRequestService/Create", ReplyAction="http://tempuri.org/IRequestService/CreateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Version))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.RequestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.UserRequestCollection))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.JusticeRequestParams[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.JusticeRequestParams))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.BaseRequestParams))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.LearningRequestParams))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.SeldonRequestParams))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.LearningRequestParams[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof( RequestService.RequestServiceReference.SeldonRequestParams[]))]
        bool Create(long UserId,  RequestService.RequestServiceReference.RequestType requestType, object requestParams);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IRequestService/Create", ReplyAction="http://tempuri.org/IRequestService/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(long UserId,  RequestService.RequestServiceReference.RequestType requestType, object requestParams);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IRequestService/GetRequests", ReplyAction="http://tempuri.org/IRequestService/GetRequestsResponse")]
         RequestService.RequestServiceReference.UserRequestCollection GetRequests(long UserId);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IRequestService/GetRequests", ReplyAction="http://tempuri.org/IRequestService/GetRequestsResponse")]
        System.Threading.Tasks.Task< RequestService.RequestServiceReference.UserRequestCollection> GetRequestsAsync(long UserId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRequestServiceChannel :  RequestService.RequestServiceReference.IRequestService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestServiceClient : System.ServiceModel.ClientBase< RequestService.RequestServiceReference.IRequestService>,  RequestService.RequestServiceReference.IRequestService {
        
        public RequestServiceClient() {
        }
        
        public RequestServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(long UserId,  RequestService.RequestServiceReference.RequestType requestType, object requestParams) {
            return base.Channel.Create(UserId, requestType, requestParams);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(long UserId,  RequestService.RequestServiceReference.RequestType requestType, object requestParams) {
            return base.Channel.CreateAsync(UserId, requestType, requestParams);
        }
        
        public  RequestService.RequestServiceReference.UserRequestCollection GetRequests(long UserId) {
            return base.Channel.GetRequests(UserId);
        }
        
        public System.Threading.Tasks.Task< RequestService.RequestServiceReference.UserRequestCollection> GetRequestsAsync(long UserId) {
            return base.Channel.GetRequestsAsync(UserId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RequestServiceReference.IRegisterService")]
    public interface IRegisterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/Register", ReplyAction="http://tempuri.org/IRegisterService/RegisterResponse")]
        bool Register(long Hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterService/Register", ReplyAction="http://tempuri.org/IRegisterService/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(long Hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterServiceChannel :  RequestService.RequestServiceReference.IRegisterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterServiceClient : System.ServiceModel.ClientBase< RequestService.RequestServiceReference.IRegisterService>,  RequestService.RequestServiceReference.IRegisterService {
        
        public RegisterServiceClient() {
        }
        
        public RegisterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(long Hash) {
            return base.Channel.Register(Hash);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(long Hash) {
            return base.Channel.RegisterAsync(Hash);
        }
    }
}
